sudo: false
language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - node_modules

env:
  - DATABASE_URL=postgres://postgres@localhost/editorial

addons:
#  postgresql: "9.3"

before_script:
  - psql -c "drop database IF EXISTS editorial;" -U postgres
  - psql -c "create database editorial;" -U postgres
  - node_modules/db-migrate/bin/db-migrate up

  - mkdir -p logs

